package com.dql.retailmanager.entity;

import java.io.Serializable;

import lombok.Data;

/**
 * null
 *
 * @TableName account
 */
@Data
public class Account implements Serializable {
    /**
     * @mbg.generated 2021-04-27 15:11:36
     */
    private Integer id;

    /**
     * @mbg.generated 2021-04-27 15:11:36
     */
    private String bankName;

    /**
     * @mbg.generated 2021-04-27 15:11:36
     */
    private Integer code;

    /**
     * @mbg.generated 2021-04-27 15:11:36
     */
    private Double initialMoney;

    /**
     * @mbg.generated 2021-04-27 15:11:36
     */
    private Double currentMoney;

    /**
     * @mbg.generated 2021-04-27 15:11:36
     */
    private String remark;

    /**
     * 账户是否在激活状态，1表示激活，0表示未激活，激活账户为临售管理的默认收款账户
     *
     * @mbg.generated 2021-04-27 15:11:36
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated 2021-04-27 15:11:36
     */
    private static final long serialVersionUID = 1L;
}