package com.dql.retailmanager.entity;

import java.io.Serializable;

import lombok.Data;

/**
 * null
 *
 * @TableName item_pic
 */
@Data
public class ItemPic implements Serializable {
    /**
     * @mbg.generated 2021-05-06 10:45:44
     */
    private Integer id;

    /**
     * @mbg.generated 2021-05-06 10:45:44
     */
    private byte[] content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_pic
     *
     * @mbg.generated 2021-05-06 10:45:44
     */
    private static final long serialVersionUID = 1L;

    public ItemPic(byte[] content) {
        this.content = content;
    }

}