package com.dql.retailmanager.entity;

import java.io.Serializable;

import lombok.Data;

/**
 * 商品表
 *
 * @TableName item
 */
@Data
public class Item implements Serializable {
    /**
     * @mbg.generated 2021-04-25 15:19:09
     */
    private Integer id;

    /**
     * @mbg.generated 2021-04-25 15:19:09
     */
    private String name;

    /**
     * @mbg.generated 2021-04-25 15:19:09
     */
    private String desc;

    /**
     * @mbg.generated 2021-04-25 15:19:09
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbg.generated 2021-04-25 15:19:09
     */
    private static final long serialVersionUID = 1L;
}