package com.dql.retailmanager.entity;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

/**
 * 物品储存情况表
 *
 * @TableName item_storage
 */
@Data
public class ItemStorage implements Serializable {
    /**
     * @mbg.generated 2021-04-25 15:19:24
     */
    private Integer itemId;

    /**
     * @mbg.generated 2021-04-25 15:19:24
     */
    private Integer storageId;

    /**
     * 现存数量
     *
     * @mbg.generated 2021-04-25 15:19:24
     */
    private Integer number;

    /**
     * 安全存量，低于这个存量预警
     *
     * @mbg.generated 2021-04-25 15:19:24
     */
    private Integer safeNumber;

    /**
     * 商品更新时间
     *
     * @mbg.generated 2021-04-25 15:19:24
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_storage
     *
     * @mbg.generated 2021-04-25 15:19:24
     */
    private static final long serialVersionUID = 1L;
}