package com.dql.retailmanager.entity;

import java.io.Serializable;
import java.util.Date;

import com.dql.retailmanager.entity.page.PageRequest;
import lombok.Data;

/**
 * null
 *
 * @TableName member
 */
@Data
public class Member implements Serializable {
    /**
     * @mbg.generated 2021-04-23 14:38:39
     */
    private Integer id;

    /**
     * @mbg.generated 2021-04-23 14:38:39
     */
    private String name = "";

    /**
     * @mbg.generated 2021-04-23 14:38:39
     */
    private String sex = "";

    /**
     * @mbg.generated 2021-04-23 14:38:39
     */
    private String address = "";

    /**
     * @mbg.generated 2021-04-23 14:38:39
     */
    private String phone = "";

    /**
     * 会员状态，可以禁用会员，1表示生效 0表示禁用
     *
     * @mbg.generated 2021-04-23 14:38:39
     */
    private Integer status = 1;

    /**
     * 注册成会员的会员编码
     *
     * @mbg.generated 2021-04-23 14:38:39
     */
    private String membernumber = "";

    private String email = "";

    private String birthdate = "";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated 2021-04-23 14:38:39
     */
    private static final long serialVersionUID = 1L;
}