package com.dql.retailmanager.entity;

import java.io.Serializable;

import lombok.Data;

/**
 * 仓库
 *
 * @TableName storage
 */
@Data
public class Storage implements Serializable {
    /**
     * @mbg.generated 2021-04-25 15:20:02
     */
    private Integer id;

    /**
     * @mbg.generated 2021-04-25 15:20:02
     */
    private String name;

    /**
     * @mbg.generated 2021-04-25 15:20:02
     */
    private String desc;

    /**
     * @mbg.generated 2021-04-25 15:20:02
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storage
     *
     * @mbg.generated 2021-04-25 15:20:02
     */
    private static final long serialVersionUID = 1L;
}