package com.dql.retailmanager.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * user table
 * @TableName User
 */
@Data
public class User implements Serializable {
    private String pwd;
    /**
     * 
     *
     * @mbg.generated 2021-04-22 11:16:12
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-04-22 11:16:12
     */
    private String name;

    /**
     * 用户类型 和用户类型表关联
     *
     * @mbg.generated 2021-04-22 11:16:12
     */
    private Integer usertypeid;

    /**
     * 
     *
     * @mbg.generated 2021-04-22 11:16:12
     */
    private String address;

    /**
     * 
     *
     * @mbg.generated 2021-04-22 11:16:12
     */
    private String phone;

    /**
     * @mbg.generated 2021-04-22 11:16:12
     */
    private String email;

    private String roleName;

    private int roleId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table User
     *
     * @mbg.generated 2021-04-22 11:16:12
     */
    private static final long serialVersionUID = 1L;
}